version: '3.9'

services:
  auth-api-db-test:
      image: postgres:17.2
      restart: always
      shm_size: 128mb
      environment:
        POSTGRES_PASSWORD: 'authapipass'
        POSTGRES_USER: 'authapi'
        POSTGRES_DB: 'auth-api'
      ports:
        - 5432:5432
      volumes:
      - db_data:/var/lib/postgresql/data
  authentication-service:
      image: auth:v2.2
      restart: always
      environment:
        DB_HOSTNAME: 'auth-api-db-test'
      ports:
        - 8080:8080
  backend-service:
      image: back:v1.2
      restart: always
      environment:
        MQ_HOSTNAME: 'rabbitmq-service'
        AUTH_HOSTNAME: 'authentication-service'
      ports:
        - 8081:8081
  cache-service:
      image: redis:7.4.2
      restart: always
      volumes:
        - ./redis.acl:/data/redis.acl
      # command: ["redis-server", "--loadmodule", "/data/redis.acl"]
      command: ["/bin/sh", "-c", "chmod 644 /data/redis.acl && redis-server --aclfile /data/redis.acl"]
      ports:
        - 6379:6379
  rabbitmq-service:
      image: rabbitmq:4.0.7-management
      restart: always
      environment:
        DB_HOSTNAME: 'auth-api-db-test'
        RABBITMQ_DEFAULT_USER: 'backUser'
        RABBITMQ_DEFAULT_PASS: 'backPassword'
      ports:
        - 8082:15672
        - 5672:5672

volumes:
  db_data:
