services:
  auth-api-db-test:
      image: postgres:17.2
      restart: always
      shm_size: 128mb
      environment:
        POSTGRES_PASSWORD: 'authapipass'
        POSTGRES_USER: 'authapi'
        POSTGRES_DB: 'auth-api'
      ports:
        - 5432:5432
      volumes:
      - db_data:/var/lib/postgresql/data
  authentication-service:
      image: auth:v2.3
      restart: always
      environment:
        DB_HOSTNAME: 'auth-api-db-test'
      ports:
        - 8082:8082
  backend-service:
      image: back:v1.14
      restart: always
      environment:
        MQ_HOSTNAME: 'rabbitmq-service'
        AUTH_HOSTNAME: 'authentication-service'
        AUTH_PORT: '8082'
        REDIS_HOSTNAME: 'cache-service'
      ports:
        - 8081:8081
  ai-operator:
      image: aiop:v1.1
      restart: always
      environment:
        REDIS_HOST: 'aicache-service'
        LLM_URL: 'http://ollama-srv:11434'
      ports:
        - 8086:8086
  aicache-service:
    image: redis/redis-stack:latest
    restart: always
    volumes:
      - ./redisai-data/redis.conf:/redis-stack.conf
      - ./redisai-data/users.acl:/users.acl:ro
    ports:
      - "6380:6380"
    # volumes:
      # - ./redisai.acl:/data/redis.acl
    # command: ["/bin/sh", "-c", "chmod 644 /data/redis.acl && redis-server --aclfile /data/redis.acl --port 6380"]
    # ports:
    #   - 6380:6380
    # redis-cli -h localhost -p 6380 -a AdminPass123   --> AUTH admin AdminPass123
  frontend-service:
      image: front:v1.3
      restart: always
      environment:
        BACKEND_URL: 'backend-service'
        BACKEND_PORT: '8081'
      ports:
        - 8085:8085
  cache-service:
      image: redis:7.4.2
      restart: always
      volumes:
        - ./redisAuth-data/redis.acl:/data/redis.acl
      # command: ["redis-server", "--loadmodule", "/data/redis.acl"]
      command: ["/bin/sh", "-c", "chmod 644 /data/redis.acl && redis-server --aclfile /data/redis.acl"]
      ports:
        - 6379:6379
  ollama-srv: 
    image: ollama/ollama:latest
    pull_policy: always
    ports: ["11435:11434"] # will be accessible in http://localhost:11435
    volumes:
      - ~/.ollama/models:/root/.ollama/models:ro 
  # rabbitmq-service:
  #     image: rabbitmq:4.0.7-management
  #     restart: always
  #     environment:
  #       DB_HOSTNAME: 'auth-api-db-test'
  #       RABBITMQ_DEFAULT_USER: 'backUser'
  #       RABBITMQ_DEFAULT_PASS: 'backPassword'
  #     ports:
  #       - 8090:15672
  #       - 5672:5672
  nginx-proxy:
      image: nginx:1.29
      ports:
        - "8080:8080"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  db_data:
