events {}

http {
    server {
        listen 8080;
        server_name localhost;

        # Proxy para la API/backend
        location /auth/ {
            rewrite ^/auth/(.*)$ /$1 break;
            proxy_pass http://backend-service:8081;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /operator/ask {
            rewrite ^/aioperator/(.*)$ /$1 break;
            proxy_pass http://ai-operator:8086/ask;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }


        # Todo lo demás va al frontend
        location / {
            proxy_pass http://frontend-service:8085/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}